name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 767397889236.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t hello-world-docker .
          docker tag hello-world-docker:latest 767397889236.dkr.ecr.eu-central-1.amazonaws.com/hello-world-docker:latest
          docker push 767397889236.dkr.ecr.eu-central-1.amazonaws.com/hello-world-docker:latest

      - name: Configure Git for pushing
        run: |
          git config --global user.email "ryan.1917@gmail.com"
          git config --global user.name "ryanredoct"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Auto-commit by GitHub Action"
          git push https://ryanredoct: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@github.com/ryanredoct/hello-world-docker.git










