name: Debugging CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Check AWS Secrets Setup
      - name: Check AWS Credentials Availability
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "ERROR: AWS_ACCESS_KEY_ID is not available!"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "ERROR: AWS_SECRET_ACCESS_KEY is not available!"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_REGION }}" ]; then
            echo "ERROR: AWS_REGION is not available!"
            exit 1
          fi
          echo "AWS credentials and region are available."
          
      # Step 2: Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Step 3: Check AWS CLI Version and Configuration
      - name: Check AWS CLI Configuration
        run: |
          aws --version
          aws sts get-caller-identity
          echo "AWS CLI is properly configured."

      # Step 4: Attempt to Log into AWS ECR and provide detailed error logging
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 767397889236.dkr.ecr.eu-central-1.amazonaws.com
        continue-on-error: true # Don't fail immediately, log the error instead

      # Step 5: Log Last Docker Command's Error if Login Fails
      - name: Check Docker ECR Login Success
        if: failure()
        run: |
          echo "ERROR: Docker login failed. Check the above logs for more details."
          docker info

      # Step 6: Build and Push Docker Image (this will only run if login succeeds)
      - name: Build and push Docker image
        run: |
          docker build -t hello-world-docker .
          docker tag hello-world-docker:latest 767397889236.dkr.ecr.eu-central-1.amazonaws.com/hello-world-docker:latest
          docker push 767397889236.dkr.ecr.eu-central-1.amazonaws.com/hello-world-docker:latest
        if: success()

      # Step 7: Log Any Build or Push Errors (if any)
      - name: Check Docker Build and Push Success
        if: failure()
        run: |
          echo "ERROR: Docker build or push failed. Check the above logs for more details."












